# Generated by Django 4.2.5 on 2023-09-26 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('fullname', models.CharField(max_length=125)),
                ('type', models.CharField(choices=[('bachelors', 'Bachelors'), ('master', 'Master')], max_length=100)),
                ('contract_amount', models.FloatField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_institute', to='students.institute')),
            ],
            options={
                'verbose_name': 'Students',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
