services:
  redis:
    container_name: metsetnat_redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis:/data

  metsenat-db:
    container_name: metsenat_db
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metsenat:
    build: ./
    container_name: metsenat_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - metsenat-db

  metsenat-worker:
    build: ./
    container_name: metsenat_worker
    command: celery --app=metsenat worker -l INFO
    volumes:
      - ./:/usr/src/app/"
    user: root
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - metsenat-db
      - redis

volumes:
  postgres_data:
  redis:

